name: blockbook
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
author: Harm Aarts <harm@aarts.email>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  mock_web_server: ^4.0.0
  pedantic: ^1.7.0
  test: ^1.6.0
