name: blockbook
description: A starting point for Dart libraries or applications.
version: 1.1.3
homepage: https://github.com/inapay/blockbook_client
author: Harm Aarts <harm@aarts.email>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+3
  web_socket_channel: ^1.1.0

dev_dependencies:
  mock_web_server:
    git: https://github.com/haarts/MockWebServer.git
  pedantic: ^1.7.0
  test: ^1.6.0
